<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

<script>
  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   console.log(res, '第一层的处理的代码');
  //
  //   return new Promise((resolve, reject) => {
  //     // resolve(res + '111')
  //     reject('err')
  //   })
  // }).then(res => {
  //   console.log(res, '第二次处理的代码');
  //
  //   return new Promise(resolve => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //   console.log(res, '第三次处理的代码');
  // }).catch(err => {
  //   console.log(err);
  // })

  // 简写： new Promise(resolve => resolve(结果))简写

  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   console.log(res, '第一层的处理的代码');
  //
  //   return Promise.resolve(res + '111')
  // }).then(res => {
  //   console.log(res, '第二次处理的代码');
  //
  //   return Promise.resolve(res + '222')
  // }).then(res => {
  //   console.log(res, '第三次处理的代码');
  // })

  // 省略掉 Promise.resolve

  // new Promise((resolve, reject) => {
  //   setTimeout(() => {
  //     resolve('aaa')
  //   }, 1000)
  // }).then(res => {
  //   console.log(res, '第一层的处理的代码');
  //
  //   return res + '111'
  // }).then(res => {
  //   console.log(res, '第二次处理的代码');
  //
  //   return res + '222'
  // }).then(res => {
  //   console.log(res, '第三次处理的代码');
  // })


  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('aaa')
    }, 1000)
  }).then(res => {
    console.log(res, '第一层的处理的代码');

    // return Promise.reject('error message')
    throw 'error message'
  }).then(res => {
    console.log(res, '第二次处理的代码');

    return res + '222'
  }).then(res => {
    console.log(res, '第三次处理的代码');
  }).catch(err => {
    console.log(err);
  })
</script>

</body>
</html>